---
apiVersion: v1
kind: Service
metadata:
 name: demo-service
 namespace: development
spec:
 selector:
  app: quote-service
 ports:
  - port: 8081
    targetPort: 8080
 type: LoadBalancer
---
apiVersion: v1
kind: Service
metadata:
 name: pod-info-service
 namespace: development
spec:
 selector:
  app: pod-info
 ports:
  - port: 81
    targetPort: 3000
 type: LoadBalancer  # or NodePort if you prefer