apiVersion: v1
kind: Service
metadata:
  name: explorecalifornia-service
  namespace: development
spec:
  type: LoadBalancer
  selector:
    app: explorecalifornia.com
  ports:
    - port: 8082
      targetPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: demo-service
  namespace: development
spec:
  selector:
    app: quote-service
  ports:
    - port: 8081
      targetPort: 8080
  type: LoadBalancer
---
apiVersion: v1
kind: Service
metadata:
  name: pod-info-service
  namespace: development
spec:
  selector:
    app: pod-info
  ports:
    - port: 8083
      targetPort: 3000
  type: LoadBalancer  # or NodePort if you prefer